package ar.com.sgt.persistence.entity;

// default package
// Generated Nov 5, 2015 12:04:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE")
public class Cliente implements java.io.Serializable {

    private Integer idcliente;
    private String usuario;
    private String pwd;
    private Integer pin;
    private String nombre;
    private String apellido;

    public Cliente() {
    }

    public Cliente(Integer idcliente) {
	this.idcliente = idcliente;
    }

    public Cliente(Integer idcliente, String usuario, String pwd, Integer pin,
	    String nombre, String apellido) {
	this.idcliente = idcliente;
	this.usuario = usuario;
	this.pwd = pwd;
	this.pin = pin;
	this.nombre = nombre;
	this.apellido = apellido;
    }

    @Id
    @Column(name = "IDCLIENTE", unique = true, nullable = false, precision = 5, scale = 0)
    public Integer getIdcliente() {
	return this.idcliente;
    }

    public void setIdcliente(Integer idcliente) {
	this.idcliente = idcliente;
    }

    @Column(name = "USUARIO", length = 40)
    public String getUsuario() {
	return this.usuario;
    }

    public void setUsuario(String usuario) {
	this.usuario = usuario;
    }

    @Column(name = "PWD", length = 40)
    public String getPwd() {
	return this.pwd;
    }

    public void setPwd(String pwd) {
	this.pwd = pwd;
    }

    @Column(name = "PIN", precision = 6, scale = 0)
    public Integer getPin() {
	return this.pin;
    }

    public void setPin(Integer pin) {
	this.pin = pin;
    }

    @Column(name = "NOMBRE", length = 40)
    public String getNombre() {
	return this.nombre;
    }

    public void setNombre(String nombre) {
	this.nombre = nombre;
    }

    @Column(name = "APELLIDO", length = 40)
    public String getApellido() {
	return this.apellido;
    }

    public void setApellido(String apellido) {
	this.apellido = apellido;
    }

}
