package ar.com.sgt.persistence.entity;

// default package
// Generated Nov 5, 2015 12:04:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Cliente generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "CLIENTE")
public class Cliente implements java.io.Serializable {

    @Id
    @Column(name = "IDCLIENTE", unique = true, nullable = false, precision = 5, scale = 0)
    private Integer idcliente;

    @Column(name = "USUARIO", length = 40)
    private String usuario;

    @Column(name = "PWD", length = 40)
    private String pwd;

    @Column(name = "PIN", precision = 6, scale = 0)
    private Integer pin;

    @Column(name = "NOMBRE", length = 40)
    private String nombre;

    @Column(name = "APELLIDO", length = 40)
    private String apellido;

    public Cliente(Integer idcliente) {
        this.idcliente = idcliente;
    }


}
